name: Circuits Meta
on:
  workflow_dispatch:
  push:
    paths: ["circuits/**", "scripts/emit_circuit_meta.py"]
jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node + snarkjs
        uses: actions/setup-node@v4
        with: {node-version: "20"}
      - run: npm i -g snarkjs
      - name: Emit circuits meta
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
          make circuits-meta
      - uses: actions/upload-artifact@v4
        with:
          name: circuits-meta
          path: artifacts/meta/
