name: Experiments Smoke
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.10"}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev] jsonschema matplotlib pyyaml
      - name: Smoke experiments
        run: |
          make exp-smoke
      - uses: actions/upload-artifact@v4
        with:
          name: exp-artifacts
          path: artifacts/
