name: Experiments Phase C Smoke
on:
  workflow_dispatch: {}
  pull_request: {}
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.10"}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev] jsonschema matplotlib pyyaml numpy
      - name: Batch curve (2 rounds)
        run: |
          make exp-batch-curve
      - name: Attacks smoke (2 rounds)
        run: |
          make exp-attacks
      - uses: actions/upload-artifact@v4
        with:
          name: phase-c-artifacts
          path: artifacts/
